<center>
<table>
	<tr>
		<th><?=$partido[$h]['name']?></th>
		<th><?=$partido[$h]['goals']?></th>
		<th><?='VS'?></th>     
		<th><?=$partido[$a]['goals']?></th>
		<th><?=$partido[$a]['name']?></th>
	</tr>
</table>
</center>
